### ISSUE TITLE
Poster preparation

### ISSUE THREAD

**Issue by mxochicale** [budai4medtech/miua2022#6]
> We will send out the instructions for you to prepare your poster sessions soon.
* [x] Select version ([latex](https://github.com/free-cortex/framework/blob/pdfs/poster.pdf) or [svg](https://github.com/mxochicale/mpg-poster/tree/master/poster))
* [x] Prepare first draft of poster (last week of June2022)
* [x] Print poster (third week of July2022)

**Comment by mxochicale** [comment]
## MIUA Poster Presentations (Abstract Track)
>From: Guang Yang <g.yang@imperial.ac.uk>
Sent: 01 July 2022 11:17
To: Yang, Guang
Cc: Michael Roberts; A.I. Aviles-Rivero; Carola-Bibiane Schönlieb
Subject: Re: MIUA Poster Presentations (Abstract Track)
> Dear authors,
Congrats again for your accepted paper(s) at MIUA 2022.
We now invite you or your colleagues to present your work at MIUA for a poster presentation.
Here are some specifications for the posters:
> 1. For the physical posters, please prepare posters in A0 size (841 x 1188 mm) in portrait to fit our poster boards. 
(We will not have facilities to print posters so participants are asked to bring their posters to the sign-in desk when registering on-site and a volunteer team member will set up the poster.)
> 2. For virtual posters, we ask that the poster image should be a non-transparent .png or .jpg file that's at least 1000 x 600 px, 16:9 aspect ratio and no larger than 3 MB. Posters can be landscapes or portraits for virtual viewing. 
> 3. To facilitate virtual participants to view our posters, all our physical posters will also need to prepare as a .png or .jpg file.
> 4. To facilitate virtual participants, we also require the leading author of each poster to prepare a pre-recorded video to introduce your work in 5 mins. Please send us your video in .mp4 format.
> 5. Please send us your poster (including the pre-recorded video) in a .zip file no later than 11 am on 15th July 2022. 
Please check our full programmes at  https://www.miua2022.com/  for more details on our poster viewing time slots.
We have no official template for your poster, but we would suggest you include our MIUA 2022 logo in your poster.
> Thanks a lot and if you have any questions please let us know.
Best wishes,
Guang (on behalf of our organising committee)

**Comment by mxochicale** [comment]
## MIUA Poster Presentations (Abstract Track)


> ________________________________________
> From: Guang Yang <g.yang @ imperial.ac.uk>
> Sent: 10 July 2022 11:07
> To: Yang, Guang
> Cc: Michael Roberts; A.I. Aviles-Rivero; Carola-Bibiane Schönlieb
> Subject: Re: MIUA Poster Presentations (Abstract Track)
> 
> Dear MIUAers,
> 
> Hope this email finds you well.
> 
> For your poster presentations, please prepare it according to the specifications as follows.
> 
> 1. Physical posters should be in A0 size in the portrait format. Please print it out and bring it to the meeting.
> 2. Everyone is also welcome to send us an e-poster, which will be put up in our GatherTown.
> 3. For all the e-posters, please prepare either an e-poster or some slides to present your work.
> 4. You can either show your picture (as a sub-window) while you are talking/presenting or you can record only the audio with your e-poster/slides.
> 5. Please send us a .zip file (with e-poster in jpg/png and your presentation in mp4).
> 6. We prefer a download link by WeTransfer. Please upload your zip via WeTransfer.
> 
> More details as follows in my last email as forwarded.
> 
> Please notice the e-poster submission deadline will be 11 am on 15th July 2022.
> 
> Thanks a lot and have a nice weekend.
> 
> 
> Best wishes,
> Guang
> 
> 
>

**Comment by mxochicale** [comment]
Hi @theabautista ,

Just sharing few updates: 
* RE: video presentation: **For all the e-posters, please prepare either an e-poster or some slides to present your work.**  So, I guess using e-poster will be straightforward for recording the video. 
* In the last commit, I added few instructions for edition of the poster using inkscape. You can download it from here for different platforms: https://inkscape.org/release/1.2/platforms/

Thanks
Miguel

**Comment by theabautista** [comment]
I'm not sure if the right poster has been uploaded? The figures seem right but the text isn't on GANs. I've written a new intro in case there wasn't an original in a new commit under drawings-v02.svg. I'm also not sure what the top row of pictures labelled 'FID' are.

**Comment by mxochicale** [comment]
You are right, drawing-v01 from [7868721](https://github.com/budai4medtech/miua2022/commit/78687217f5023a5d098719d6f8cc98b0bea8dcd1) was only a template for the poster. I have just added further updates from the ones you shared for drawing-v02 and committed drawing-v03. Feel free to make further changes and hopefully you won't have problems committing drawing-v04.
Thanks

**Comment by mxochicale** [comment]
> Thursday 28th July 2022
> — Empirical Study of Quality Image Assessment for Synthesis of Fetal Head
Ultrasound Imaging with DCGANs https://www.miua2022.com/images/MIUA2022Programmee_Full_FinalV2.pdf
